@startuml
object ModelAccessor
object SurrogateModel
object DriftAnalyzer
object PreProcessor


object original_test_df
object target_value
object predictor
object feature_importance
object new_test_df

ModelAccessor o-- original_test_df
ModelAccessor o-- target_value
ModelAccessor o-- predictor
predictor o-- feature_importance
predictor *-- SurrogateModel
SurrogateModel o-- DriftAnalyzer
PreProcessor o-- DriftAnalyzer
PreProcessor o-- original_test_df
new_test_df o-- DriftAnalyzer

@enduml
